O	40 K
#	   F
T	   Z

A	45 @
U	 4 @
A	22 @
T	39 @
[A	   F]
E	 8 @
O	40 @
O	41 @
T	 4 @
A	   D

E	15 @
T	   D
S	   D
O	   @
E	16 @
O	42 @
P	   H
T	   D
H	44 @
A	 4 @

T	 4 @
V	   D
U	 1 F
O	 1 F
F	   F
S	   F
G	29 @
S	43 @
G	30 @
O	41 @

A	43 @
L	 4 F
T	   D
A	 4 @
L	   D
E	20 @
O	42 @
L	   D
G	20 @
[E	   F]

@	   F
&	   F
!	   F
Q	   F
J	   F
P	 2 F
