T Z

A	 3 F
T	30 @
T	 4 H
S	31 @
A	32 @
U	16 @
A	33 @
T	 J @
A	   H
H	 2 H

[V	   F]
Y	   F
T	   D
A	13 @
G	   N
H	   D
[V	   F]
Y	   F
A	 4 H
T	 4 H

A	 J @
A	34 @
G	 7 @
S	35 @
G	 4 @
H	 4 H
V	 2 H
L	   D
Y	   F
T	   D

[E	   F]
~~~~~~~~~
P	 6 F
V	42 #@
M	 6 F
O	   F
I	46 #@
E	69 K
T	36 #@

  14716 66184 F
  30989 18315 F
  40193 50093 F
1 60197 04270 F
1 13594 90762 F
  40994 46400 #

T	48 Z
