......
P K
T 60 K

G K

A	 3 F
T	34 @
S	 4 D
E	13 @
T	 4 D
S	   D
T	   D
E	 2 @
T	 4 D
A	   D

L	   D
T	   D
A	 4 D
L	   D
E	 8 @
R	   D
U	 4 D
L	   D
A	35 @
T	 6 D

E	25 @
U	 8 D
N	 8 D
A	 6 D
T	 6 D
H	 6 D
S	 6 D
N	 4 D
A	 4 D
Y	   F

G	21 @
S	   D
V	   D
T	   D
[E	   F]
W 1526 D
......
P K
T 100 K

G	   K

A	 3 F
T	26 @
H	28 #@
N	   D
Y	   F
L	   D
T	 4 D
S	27 @
T	   F
H	 8 @

S	 8 @
T	 1 F
V	 4 D
A	   F
G	31 @
S	   F
L	   D
U	   F
O	   F
F	   F

S	   F
L	 4 F
T	 4 D
A	 1 F
A	27 @
G	11 @
[Z	   F]

T	28 #Z
P	   F
T	27 Z

P 1024 F
P  610 D
@ 524 D

!	   F
O	30 @
S	   F
L	 8 F
E	22 @
.......
PKGK

P 2048 F
P 10000 F
# F
@ F
& F

O 2 @
A 0 @
T F
T 1 F
A 1 @
T 4 F
T 5 F
A 12 @
G 60 F
X D
X F
X 1 F
A 17 @
G 100 F
O 3 @
O 4 @
O 4 @
Z F

E 5 Z P F
